show_logs: True
log_level: 6

wandb:
  entity: "auditory-grounding"
  project: "try"

data_params:
  dataset_path: '../../data/timbre'
  batch_size: 32 # set this number twice as actual batch size
  num_workers: 0

  spectrogram:
    type: "stft" # "stft" or "mel"
    stft:
      spectrogram_dims: [512, 64]
      hop_length: 256
    mel:
      frame_size: 1024
      hop_length: 256
      spectrogram_dims: [80, 63] # (mel_channels, n_frames)
      segment_signal_length: 16000
  saver: # saves spectrogram as npy and min/max values. TODO: Untested
    enabled: False
    save_dir: "../out" # relative to dataset_path
  visualizer:
    enabled: False # Please enable for spectrogram inference
    save_dir: "../out" # relative to dataset_path
  csv: # Log generated datapoints in a csv
    enabled: True
    path: "../log" # relative to dataset_path



model_params:
  name: 'TimbreTransfer'
  timbre_encoder:
    spectrogram_dims: [1, 512, 64] # (C, H, W). dependant on data_params.spectrogram....
    conv2d_channels: [128, 64, 32, 16]
    stride: [2, 2]
    kernel_size: [7, 7] # 5X5 needs padding=2, and 7X7 needs padding=3. All when stride=2
    padding: [3, 3]
    latent_dim: 256
    converge_latent: "first" # TODO: not used
  loss:
    function: "L1"
  merge_encoding: "sandwich" # z di_b z
  decoder:
    di_spectrogram_dims: [1, 512, 64] # (C, H, W). dependant on data_params.spectrogram....
    conv2d_channels: [32, 8, 2, 1] # These are conv2d channels. Encoder: (1, 256, 64) -> (32, 128, 32) -> (64, 64, 16) -> (128, 32, 8) -> (256, 16, 4) -> (512, 8, 2)
    stride: [1, 1]
    kernel_size: [5, 5]
    padding: [2, 2]
#  load_path: "/work/gk77/k77021/repos/TimbreSpace/logs/TimbreTransfer/version_4/checkpoints/last.ckpt"


exp_params:
  LR: 0.0001
  weight_decay: 0.0
  kld_weight: 0.000001
  manual_seed: 1265
  model_checkpoint: # Diecrtly passed to ModelCheckpoint()
    save_top_k: 10
    every_n_epochs: 30
    monitor: "val_loss"
    save_last: True



trainer_params: # This directly goes to trainer
  gpus: []
  max_epochs: 2000
  log_every_n_steps: 10


logging_params:
  save_dir: "logs/"
